-- liquibase formatted sql

-- changeset postgres:1
CREATE TABLE users
(
    id            BIGINT generated by default as identity primary key,
    telegram_id   BIGINT   NOT NULL,
    telegram_nick TEXT,
    first_name    TEXT,
    last_name     TEXT,
    phone_number  TEXT,
    user_type     SMALLINT NOT NULL
);